#!/bin/sh

set -eu

[ -d ".git" ]
[ -n "${GENSHIN_DATA_REPO-}" ]
[ -d "${GENSHIN_DATA_REPO}/.git" ]

NAME="$1"
COMMIT="$2"
OUT="$PWD/$NAME"

git -C "$GENSHIN_DATA_REPO" worktree add --detach --no-checkout -- "$OUT" "$COMMIT"
mv -- "$OUT/.git" "$OUT/.git.tmp"

for pathspec in \
	BinOutput/Ability/Temp/AvatarAbilities \
	BinOutput/Ability/Temp/ConfigAbility_Element.json \
	BinOutput/Ability/Temp/EquipAbilities \
	BinOutput/Avatar \
	BinOutput/Gadget \
	BinOutput/Talent; do
	git -C "$OUT" --git-dir ".git.tmp" checkout HEAD -- "$pathspec"
	git add -v -- "$NAME/$pathspec" > /dev/null
done

mv -- "$OUT/.git.tmp" "$OUT/.git"
git -C "$GENSHIN_DATA_REPO" worktree remove --force -- "$OUT"

git checkout -- "$NAME"

NPROC="$(nproc --ignore=1)"
# shellcheck disable=SC2016
git ls-files -z -- "$NAME/*.json" | xargs -0 -L1 -P "$NPROC" sh -c 'set -eu; jq . -- "$0" > /dev/null; jq . -- "$0" | sponge -- "$0"'
# shellcheck disable=SC1003,SC2016
git ls-files -z -- "$NAME" ':!:*.json' | xargs -0 -L1 -P "$NPROC" sed -i '$a\' --
git ls-files -z -- "$NAME" ':!:*.json' | xargs -0 -L1 -P "$NPROC" dos2unix -q --

git ls-files -z -- "$NAME" | xargs -0 git add -v --
